# Generated by Django 5.2.7 on 2025-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending ', 'в работе'), ('accepted ', 'принят'), ('rejected ', 'отклонён')], default='new', max_length=10),
        ),
    ]
